### ISSUE TITLE
error: SharedIniFileCredentialsProviderFailure: Credentials not set for profile [redacted]

### ISSUE THREAD

**Issue by mathenshall** [whilenull/7777-support#62]
It still works, just displays the error below.

I've had this since I first started using 7777 a year or so ago, and I think we had an email conversation about it. Just updated to the latest version, and it still is happening. It still works, but my colleagues at every client I go to are always a bit nervous about using a tool that spits out an error.

Using macos

We use the standard `aws sso login` with profile approach. and set the profile name in AWS_PROFILE

```SharedIniFileCredentials {
  expired: false,
  expireTime: null,
  refreshCallbacks: [],
  accessKeyId: undefined,
  sessionToken: undefined,
  filename: undefined,
  profile: 'vibrant-dev-dev',
  disableAssumeRole: false,
  preferStaticCredentials: false,
  tokenCodeFn: [AsyncFunction: f],
  httpOptions: null
} error: SharedIniFileCredentialsProviderFailure: Credentials not set for profile [redacted
    at SharedIniFileCredentials.load (/snapshot/7777/node_modules/aws-sdk/lib/credentials/shared_ini_file_credentials.js:146:11)
    at SharedIniFileCredentials.coalesceRefresh (/snapshot/7777/node_modules/aws-sdk/lib/credentials.js:205:12)
    at SharedIniFileCredentials.refresh (/snapshot/7777/node_modules/aws-sdk/lib/credentials/shared_ini_file_credentials.js:170:10)
    at SharedIniFileCredentials.get (/snapshot/7777/node_modules/aws-sdk/lib/credentials.js:122:12)
    at /snapshot/7777/node_modules/aws-sdk/lib/util.js:865:26
    at new Promise (<anonymous>)
    at SharedIniFileCredentials.promise [as getPromise] (/snapshot/7777/node_modules/aws-sdk/lib/util.js:857:14)
    at Object.awsSdkMfa (/snapshot/7777/lib/hooks/AwsSdkMfa.js:18:21)
    at /snapshot/7777/node_modules/@oclif/config/lib/config.js:151:46
    at Array.map (<anonymous>) {
  code: 'SharedIniFileCredentialsProviderFailure',
  time: 2024-09-18T22:51:04.678Z
```

**Comment by mnapoli** [comment]
Hi! Thanks for bringing this up again, I've pushed a new version that should fix this!
